services:
  ringremote:
    image: ghcr.io/yanorei32/ring-remote:latest@sha256:6d8b4fa534f43edc383208077597800472e3be10b3fb9252d7512e8d301c16ba
    hostname: ringremote
    container_name: ringremote${VARIANT:-}__ringremote
    restart: unless-stopped

    environment:
      LISTEN: 0.0.0.0:3000
      TARGET: ${TARGET}

    command: /usr/bin/ring-remote

    deploy:
      resources:
        limits:
          memory: 128m

    networks:
      - default

  cloudflared:
    image: cloudflare/cloudflared:2026.9.1@sha256:b269e8abd07a5bf6f3f4be65d5050b2174eca89c56a0241a8ff32a16aec454e4
    hostname: cloudflared
    container_name: ringremote${VARIANT:-}__cloudflared

    restart: unless-stopped

    environment:
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}
    user: root

    deploy:
      resources:
        limits:
          memory: 128m

    networks:
      default:

networks:
  default:
    name: ringremote${VARIANT:-}__default
