services:
  ringremote:
    image: ghcr.io/yanorei32/ring-remote:latest@sha256:9726865d96f9eed290f5aaabf7cdd81e0d5fbea6febf39b3937f36a3448d17f3
    hostname: ringremote
    container_name: ringremote${VARIANT:-}__ringremote
    restart: unless-stopped

    environment:
      LISTEN: 0.0.0.0:3000
      TARGET: ${TARGET}

    command: /usr/bin/ring-remote

    deploy:
      resources:
        limits:
          memory: 128m

    networks:
      - default

  cloudflared:
    image: cloudflare/cloudflared:2026.8.2@sha256:0aa26e284f05e6c77ae375b8c9c11d9eb6a448fb7bcd8d40f31cb6176189eb38
    hostname: cloudflared
    container_name: ringremote${VARIANT:-}__cloudflared

    restart: unless-stopped

    environment:
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}
    user: root

    deploy:
      resources:
        limits:
          memory: 128m

    networks:
      default:

networks:
  default:
    name: ringremote${VARIANT:-}__default
