services:
  ringremote:
    image: ghcr.io/yanorei32/ring-remote:latest@sha256:9726865d96f9eed290f5aaabf7cdd81e0d5fbea6febf39b3937f36a3448d17f3
    hostname: ringremote
    container_name: ringremote${VARIANT:-}__ringremote
    restart: unless-stopped

    environment:
      LISTEN: 0.0.0.0:3000
      TARGET: ${TARGET}

    command: /usr/bin/ring-remote

    deploy:
      resources:
        limits:
          memory: 128m

    networks:
      - default

  cloudflared:
    image: cloudflare/cloudflared:2026.6.1@sha256:6d91c121b803126f7a5344005d17a9324788fc09d305b6e2560ec6040a7ae283
    hostname: cloudflared
    container_name: ringremote${VARIANT:-}__cloudflared

    restart: unless-stopped

    environment:
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}
    user: root

    deploy:
      resources:
        limits:
          memory: 128m

    networks:
      default:

networks:
  default:
    name: ringremote${VARIANT:-}__default
